const tourActionTypes = {
  FETCH_TOURS_START_ASYNC: 'FETCH_TOURS_START_ASYNC',
  FETCH_TOURS_START: 'FETCH_TOURS_START',
  FETCH_TOURS_SUCCESS: 'FETCH_TOURS_SUCCESS',
  FETCH_TOURS_FAILURE: 'FETCH_TOURS_FAILURE',
  FETCH_TOUR_START_ASYNC: 'FETCH_TOUR_START_ASYNC',
  FETCH_TOUR_START: 'FETCH_TOUR_START',
  FETCH_TOUR_SUCCESS: 'FETCH_TOUR_SUCCESS',
  FETCH_TOUR_FAILURE: 'FETCH_TOURS_FAILURE'
};
export default tourActionTypes;
